stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw.csv
    - src/prepare.py
    params:
    - seed
    outs:
    - data/test.csv
    - data/train.csv
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/test.csv
    - data/train.csv
    - src/preprocess.py
    outs:
    - data/test_processed.csv
    - data/train_processed.csv
  catboost_training:
    cmd: python src/catboost_train.py
    deps:
    - data/train_processed.csv
    - src/catboost_train.py
    outs:
    - models/catboost.joblib
  catboost_evaluation:
    cmd: python src/evaluate.py models/catboost.joblib
    deps:
    - data/test_processed.csv
    - src/evaluate.py
    metrics:
    - metrics.json
    plots:
    - plots
